### ISSUE TITLE
Request: APK for ARMv7

### ISSUE THREAD

**Issue by antermin** [oupson/jxlviewer#1]
After discovering your project, I shared the repo in [JPEG XL Discord](https://discord.gg/DqkQgDRTFu). Members reported that the app works very well.

I would also like to try the app, but I couldn't as my devices are ARMv7 while the APK is for ARM64. Can you please build the app for ARMv7?

Thank you very much for making jxlviewer - it is amazing as there are only very few Android apps which can open JXL files.

**Comment by oupson** [comment]
Hello, thanks for sharing and sorry for the late reply. I will try to release an apk for all arch (thanks to the work of @8cAyqpVKio) soon.
