### ISSUE TITLE
Color profile support

### ISSUE THREAD

**Issue by antermin** [oupson/jxlviewer#14]
The app currently does not support color profile in JXL file, so if I load the [bench_oriented_BRG](https://github.com/libjxl/conformance/tree/master/testcases/bench_oriented_brg) test file, colors are wrong (e.g. the bench is green).

**Comment by oupson** [comment]
![Screenshot_20221220-191431](https://user-images.githubusercontent.com/31827294/208738336-b43686f7-2693-44f8-8a27-1d477ca57d36.png)

Seems fixed

**Comment by oupson** [comment]
Yes, I will release a new version soon with the fix.
