### ISSUE TITLE
JXL-viewer Appears as Option to Open .apk and .pdf

### ISSUE THREAD

**Issue by OkyDooky** [oupson/jxlviewer#16]
On an Android 9 (stock OS) device, I downloaded an .apk and when I tapped on it to install it and both JXL-viewer and the session installer came up as options.
This sounds unintended.

**Comment by oupson** [comment]
I can't reproduce. Can you tell me what ROM are you running on which device please ?

**Comment by OkyDooky** [comment]
Already said which ROM. Device is Moto G7 Supra (Power rebrand).

I'll try to reproduce it, since I tapped "Always Use" for the session installer on the second time the dialogue came up.
The file explorer I used was Amaze.

**Comment by OkyDooky** [comment]
So, I couldn't quickly find a way to clear the default from the "Package installer" (I guess I got the "session installer" terminology from somewhere else), so I tried uninstalling and reinstalling the JXL viewer, but it still would default to the package installer, even in Amaze.
However, if I tap the three dots next to the .apk file in Amaze and select "Open with" and then, when it shows the "Open As" menu, select "Other," it displays Jpeg XL Viewer as a secondary option.

**Comment by OkyDooky** [comment]
And just confirned on my second device that this app comes up as an option for apk files.
I downloaded ImgurViewer from Github using Bromite and tapped on the notification once it finished, then Package installer, Jpeg XL Viewer, [App Manager](https://f-droid.org/packages/io.github.muntashirakon.AppManager/), and [OpenDocumentReader](https://f-droid.org/packages/at.tomtasche.reader/) came up as options on that device.
Doubly confirmed when opening Amaze, selecting the file, and then selecting the "Install" option.
This second device is a Galaxy Note 3 (T-Mobile version) running a currently outdated version of Lineage (14.1) which translates to Android version 7.1.2.

**Comment by oupson** [comment]
Can reproduce on EMUI 8.0.0. Thanks for the report !

**Comment by OkyDooky** [comment]
No problem! Glad it was reproducable for you. It's not a big deal nor does it break anything, but it was odd and a little funny seeing it listed like that. Glad I could help. :)

**Comment by OkyDooky** [comment]
Oh, lmao. It seems your app's versatility knows no bounds. XD Haha!
![Screenshot_2022-12-27_19-42-07](https://user-images.githubusercontent.com/59938024/209754072-17cee601-ac69-4e9d-8869-afbe56c2ceb0.png)

**Comment by oupson** [comment]
Argh :smile: 

I hate android intent pickers.

**Comment by oupson** [comment]
> The attribute pathSuffix was introduced in API Level 31.
From [https://developer.android.com/guide/topics/manifest/data-element](documentation)

Android Studio ... where are my warnings ?

**Comment by oupson** [comment]
@OkyDooky can you try with this apk and tell me if the problem still exist ?
Thanks in advance.

[apk](https://oupson.fr/jxlviewer/app-universal-release-pre0.2.3.apk)

**Comment by OkyDooky** [comment]
Downloaded. Just to confirm, this is the new JXL-Viewer app and you want me to see if the "tap on apk and get the viewer as an option" still exists, correct?

**Comment by oupson** [comment]
Yes, this is a version built from latest commit in main and that should fix the issue. It should not show when you try to open pdf or zip files.

**Comment by oupson** [comment]
I tried on my old device and it seems to confirm the issue. I would like a confirmation on your own if you have the time.

**Comment by OkyDooky** [comment]
The new apk seems to have resolved the issue (at least with those formats). I'll reopen this if any new ones appear. Glad it got resolved!

**Comment by OkyDooky** [comment]
Heh. You'll be "pleased" to know that on my other device, which hasn't used the test build you provided here, it's also appeared as an option for opening my phone dialer. XD
