### ISSUE TITLE
fails to load file

### ISSUE THREAD

**Issue by Djfe** [oupson/jxlviewer#22]
the viewer fails to load this file
[Rubin golden vase 1](https://jpegxl.info/art/2021-08_totocaca.jxl) from https://jpegxl.info/art/

I installed ARMv8 on a Pixel 7 Pro Android 13

I know this viewer just uses libjxl. if you tell me it's not a bug in the viewer itself, I'll report a bug over there.
the thing ks: I don't know any way to verify whether this is a valid jxl. (under the finalized jxl spec)

**Comment by oupson** [comment]
jxlinfo give this informations :  
```
JPEG XL image, 320x320, (possibly) lossless, 10-bit RGB
num_color_channels: 3
num_extra_channels: 0
have_preview: 0
have_animation: 0
Intrinsic dimensions: 320x320
Orientation: 1 (Normal)
Color space: RGB, D65, sRGB primaries, sRGB transfer function, rendering intent: Relative
```

djxl can't decode it :
```
JPEG XL decoder v0.8.2 954b4607 [AVX2,SSE4,SSSE3,Unknown]
Read 81 compressed bytes.
Failed to decode image
DecompressJxlToPackedPixelFile failed
```

**Comment by oupson** [comment]
Well ... https://github.com/libjxl/libjxl/issues/2171

**Comment by Djfe** [comment]
ok, that's funny.
The patch has been merged in april. Looks like it might end up in the next full release of libjxl (v0.9), whenever that will be. Thanks for taking a look.
