### ISSUE TITLE
ABI ARMv9

### ISSUE THREAD

**Issue by Djfe** [oupson/jxlviewer#23]
Which ABI are users on ARMv9 supposed to install? :) 
none, yet?

**Comment by oupson** [comment]
Honestly I have no idea. As it seems to be a 64 bits arch, probably [app-arm64-v8a-release.apk](https://github.com/oupson/jxlviewer/releases/download/0.3.0/app-arm64-v8a-release.apk), but you can also try the [universal variant](https://github.com/oupson/jxlviewer/releases/download/0.3.0/app-universal-release.apk).

**Comment by Djfe** [comment]
I don't have a v9 phone, yet 😅
I was just wondering, why v9 didn't exist. but yeah, if most plattform code just depends on general arch and 32 vs 64bit then v8 and v9 might be similar and it doesn't matter :)
